version: '3.1'

services:
  mongo:
    image: mongo:4.0.20-xenial
    container_name: mongo_work_org
    volumes:
      - mongodb-data:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpass
  work_organizer:
    build: .
    container_name: work_organizer
    ports:
      - 3000:3000
    depends_on:
      - mongo

volumes:
  mongodb-data:
